#!/usr/bin/env python3
"""Generate Incus schemas offline; update explicitly with --download --ref vX.Y.Z."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
LIBRARY = ROOT
REF = "v7.0.1"
SOURCES = {
    "rest-api.yaml": "doc/rest-api.yaml",
    "configuration.json": "internal/server/metadata/configuration.json",
}
RESERVED = set("abstract amends as class const else extends external false fixed for function hidden if import in is let local module new nothing null open out outer read super this throw trace true typealias unknown when".split())
ALIASES = {"ConfigMap": "Mapping<String, String>", "DevicesMap": "Mapping<String, Mapping<String, String>>"}
# Go fields without YAML tags are lowercased by the YAML decoder.
YAML_NAMES = {
    "InitNetworksProjectPost": {"Project": "project"},
    "InitProfileProjectPost": {"Project": "project"},
    "InitStorageVolumesProjectPost": {"Project": "project", "Pool": "pool"},
}


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def ident(name):
    return name if re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", name) and name not in RESERVED else f"`{name}`"


def title(name):
    return "".join(x[:1].upper() + x[1:] for x in re.split(r"[^a-zA-Z0-9]+", name) if x)


def docs(value):
    return [f"/// {line}".rstrip() for line in str(value or "").strip().splitlines()]


class Generator:
    def __init__(self, definitions, ref):
        self.definitions, self.ref = definitions, ref
        self.aliases, self.inline, self.fallbacks = dict(ALIASES), {}, []

    def flatten(self, schema, seen=()):
        if "$ref" in schema:
            name = schema["$ref"].rsplit("/", 1)[-1]
            if name in seen:
                raise ValueError(f"Cyclic inheritance: {seen} -> {name}")
            return self.flatten(self.definitions[name], (*seen, name))
        result = {k: v for k, v in schema.items() if k != "allOf"}
        result["properties"] = dict(result.get("properties", {}))
        for part in schema.get("allOf", []):
            parent = self.flatten(part, seen)
            result["properties"] = {**parent.get("properties", {}), **result["properties"]}
            result["required"] = sorted(set(result.get("required", [])) | set(parent.get("required", [])))
        return result

    def type(self, schema, owner, name, refs):
        if "$ref" in schema:
            ref = schema["$ref"].rsplit("/", 1)[-1]
            if ref in self.aliases:
                if owner != "Types":
                    refs.add("Types")
                return ref if owner == "Types" else f"Types.{ref}"
            if ref == owner:
                return "module"
            if ref not in self.definitions and ref not in self.inline:
                raise ValueError(f"Unresolved schema reference {ref}")
            refs.add(ref)
            return ref
        enum = schema.get("enum")
        if enum and all(isinstance(x, str) for x in enum):
            return " | ".join(quote(x) for x in enum)
        if "oneOf" in schema or "anyOf" in schema:
            return " | ".join(dict.fromkeys(self.type(x, owner, name + str(i), refs) for i, x in enumerate(schema.get("oneOf", schema.get("anyOf")))))
        kind = schema.get("type")
        simple = {"string": "String", "integer": "Int", "number": "Number", "boolean": "Boolean"}
        if kind in simple:
            return simple[kind]
        if kind == "array":
            return f"Listing<{self.type(schema.get('items', {}), owner, name + 'Item', refs)}>"
        if schema.get("properties") or schema.get("allOf"):
            nested = owner + title(name)
            if nested in self.definitions:
                nested += "Inline"
            self.inline[nested] = self.flatten(schema)
            refs.add(nested)
            return nested
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"Mapping<String, {self.type(additional, owner, name + 'Value', refs)}>"
        if kind == "object" or additional is True:
            return "Mapping<String, Any>"
        self.fallbacks.append(f"{owner}.{name}")
        return "Any"

    def header(self):
        return f"// Generated by scripts/gen-incus-pkl.py from Incus {self.ref}.\n// Sources and SHA-256: ../sources/lock.json. Do not edit.\n\n"

    def module(self, name, schema):
        refs, fields = set(), []
        schema = self.flatten(schema)
        for prop, s in sorted(schema.get("properties", {}).items()):
            fields += docs(s.get("description"))
            if s.get("readOnly"):
                fields += ["/// Read-only API response field."]
            field = YAML_NAMES.get(name, {}).get(prop, prop)
            typ = self.type(s, name, prop, refs)
            if prop not in schema.get("required", []) or s.get("x-nullable"):
                typ = f"({typ})?" if " | " in typ else f"{typ}?"
            fields += [f"{ident(field)}: {typ}", ""]
        head = docs(schema.get("description", schema.get("title")))
        head += [f"open module incus.api.{name}", ""]
        head += [f'import "{ref}.pkl"' for ref in sorted(refs)]
        return self.header() + "\n".join(head + [""] + fields).rstrip() + "\n"

    def generate(self):
        files = {}
        for name, schema in self.definitions.items():
            if name not in self.aliases and schema.get("type") not in ("object", None) and not schema.get("properties"):
                self.aliases[name] = "pending"
        lines, refs = ["module incus.api.Types", ""], set()
        for name in sorted(self.aliases):
            typ = ALIASES.get(name) or self.type(self.definitions[name], "Types", name, refs)
            self.aliases[name] = typ
            lines += docs(self.definitions.get(name, {}).get("description"))
            lines += [f"typealias {name} = {typ}", ""]
        lines[2:2] = [f'import "{r}.pkl"' for r in sorted(refs)] + [""]
        files["api/Types.pkl"] = self.header() + "\n".join(lines).rstrip() + "\n"
        for name, schema in sorted(self.definitions.items()):
            if name not in self.aliases:
                files[f"api/{name}.pkl"] = self.module(name, schema)
        done = set()
        while set(self.inline) - done:
            name = sorted(set(self.inline) - done)[0]
            files[f"api/{name}.pkl"] = self.module(name, self.inline[name])
            done.add(name)
        return files


def option_modules(metadata, header):
    result, catalog = {}, {}
    for family, groups in sorted(metadata["configs"].items()):
        batches = {family: groups} if family != "devices" else {"device_" + k: {k: v} for k, v in groups.items()}
        for batch, subgroups in batches.items():
            name, options = title(batch) + "Options", {}
            for group in subgroups.values():
                for item in group["keys"]:
                    options.update(item)
            lines = [f"open module incus.options.{name}", "", 'extends "Options.pkl"', ""]
            for key, info in sorted(options.items()):
                if "*" in key or any(part in {"NAME", "ARCHITECTURE", "POOL_NAME"} for part in key.split(".")):
                    continue
                typ = {"bool": "Boolean", "integer": "Int", "int": "Int", "int64": "Int"}.get(info.get("type"), "String")
                lines += docs(info.get("shortdesc")) + docs(info.get("longdesc"))
                lines += [f"{ident(key)}: {typ}?", ""]
            result[f"options/{name}.pkl"] = header + "\n".join(lines).rstrip() + "\n"
            catalog[name] = options
    result["options/Options.pkl"] = header + '''open module incus.options.Options

/// Explicit raw keys, including user.* and options added by newer servers.
hidden extra: Mapping<String, String> = new {}

/// Convert only the explicitly supplied options into Incus string values.
function toConfigMap(): Mapping<String, String> = let (values = this.toDynamic().toMap()) new {
  for (key, value in values) {
    when (value != null) {
      [key] = value.toString()
    }
  }
  for (key, value in extra) {
    [key] = value
  }
}
'''
    return result, catalog


def generate(source, ref):
    doc = yaml.safe_load((source / "rest-api.yaml").read_text())
    if doc.get("swagger") != "2.0":
        raise ValueError("Expected Swagger 2.0")
    gen = Generator(doc["definitions"], ref)
    files = gen.generate()
    options, catalog = option_modules(json.loads((source / "configuration.json").read_text()), gen.header())
    files.update(options)
    facade = [f"// Generated from Incus {ref}; see spec/sources/lock.json.", "module incus.Incus", ""]
    for path in sorted(files):
        name = Path(path).stem
        if name not in ("Types", "Options"):
            facade += [f'import "spec/{path}" as _{name}']
    facade += ['import "spec/api/Types.pkl" as Types', ""]
    for path in sorted(files):
        name = Path(path).stem
        if name not in ("Types", "Options"):
            facade += [f"typealias {name} = _{name}"]
    facade += [f"typealias {name} = Types.{name}" for name in sorted(gen.aliases)]
    report = {"ref": ref, "definitions": sorted(doc["definitions"]), "inline_models": sorted(gen.inline), "option_modules": {n: len(v) for n, v in catalog.items()}, "untyped_fields": sorted(set(gen.fallbacks)), "yaml_field_overrides": YAML_NAMES}
    files["coverage.json"] = json.dumps(report, indent=2, sort_keys=True) + "\n"
    shapes = {name: sorted(YAML_NAMES.get(name, {}).get(p, p) for p in gen.flatten(s).get("properties", {})) for name, s in doc["definitions"].items() if name not in gen.aliases}
    files["api-shapes.json"] = json.dumps(shapes, indent=2, sort_keys=True) + "\n"
    return files, "\n".join(facade) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ref", default=REF)
    parser.add_argument("--source-dir", type=Path, default=LIBRARY / "spec/sources")
    parser.add_argument("--output-dir", type=Path, default=LIBRARY)
    parser.add_argument("--download", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.download and args.check:
        parser.error("--download and --check are mutually exclusive")
    if args.download:
        args.source_dir.mkdir(parents=True, exist_ok=True)
        for name, path in SOURCES.items():
            with urllib.request.urlopen(f"https://raw.githubusercontent.com/lxc/incus/{args.ref}/{path}", timeout=60) as response:
                (args.source_dir / name).write_bytes(response.read())
    lock = {"ref": args.ref, "sources": {name: {"url": f"https://raw.githubusercontent.com/lxc/incus/{args.ref}/{path}", "sha256": hashlib.sha256((args.source_dir / name).read_bytes()).hexdigest()} for name, path in SOURCES.items()}}
    lockpath = args.source_dir / "lock.json"
    if lockpath.exists() and not args.download and json.loads(lockpath.read_text()) != lock:
        raise ValueError("Source lock mismatch; use the pinned ref or explicitly --download")
    files, facade = generate(args.source_dir, args.ref)
    outputs = {args.output_dir / "spec" / p: s for p, s in files.items()}
    outputs[args.output_dir / "Incus.pkl"] = facade
    outputs[args.output_dir / "spec/sources/lock.json"] = json.dumps(lock, indent=2, sort_keys=True) + "\n"
    bad = []
    for folder in ("api", "options"):
        for path in (args.output_dir / "spec" / folder).glob("*.pkl"):
            if path not in outputs:
                if args.check:
                    bad.append(str(path) + " (obsolete generated file)")
                else:
                    path.unlink()
    for path, value in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != value:
                bad.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(value)
    if bad:
        print("Generated files differ:\n" + "\n".join(bad), file=sys.stderr)
        return 1
    print(f"{'Checked' if args.check else 'Generated'} {len(outputs)} files for Incus {args.ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
